ALTER TABLE store_page_revision
    ADD COLUMN detailed_description TEXT NULL AFTER short_description,
    ADD COLUMN localizations_json TEXT NULL AFTER detailed_description,
    ADD COLUMN genres_json TEXT NULL AFTER localizations_json,
    ADD COLUMN tags_json TEXT NULL AFTER genres_json,
    ADD COLUMN developer VARCHAR(200) NULL AFTER tags_json,
    ADD COLUMN publisher VARCHAR(200) NULL AFTER developer,
    ADD COLUMN screenshots_json TEXT NULL AFTER publisher,
    ADD COLUMN trailers_json TEXT NULL AFTER screenshots_json,
    ADD COLUMN icon_url VARCHAR(500) NULL AFTER trailers_json,
    ADD COLUMN cover_url VARCHAR(500) NULL AFTER icon_url,
    ADD COLUMN supported_languages_json TEXT NULL AFTER cover_url,
    ADD COLUMN recommended_requirements VARCHAR(1000) NULL AFTER minimum_requirements,
    ADD COLUMN features_json TEXT NULL AFTER recommended_requirements,
    ADD COLUMN support_url VARCHAR(500) NULL AFTER features_json,
    ADD COLUMN privacy_policy_url VARCHAR(500) NULL AFTER support_url,
    ADD COLUMN eula_url VARCHAR(500) NULL AFTER privacy_policy_url,
    ADD COLUMN sales_countries_json TEXT NULL AFTER eula_url,
    ADD COLUMN prices_json TEXT NULL AFTER sales_countries_json,
    ADD COLUMN status VARCHAR(20) NOT NULL DEFAULT 'PUBLISHED' AFTER prices_json,
    ADD COLUMN published_at DATETIME(6) NULL AFTER status,
    ADD COLUMN entity_version BIGINT NOT NULL DEFAULT 0 AFTER published_at;

UPDATE store_page_revision
SET detailed_description = short_description,
    localizations_json = '{}',
    genres_json = '[]',
    tags_json = '[]',
    developer = '',
    publisher = '',
    screenshots_json = '[]',
    trailers_json = '[]',
    supported_languages_json = '[]',
    recommended_requirements = minimum_requirements,
    features_json = '[]',
    support_url = '',
    privacy_policy_url = '',
    eula_url = '',
    sales_countries_json = '["KR"]',
    prices_json = '{}',
    published_at = created_at;

ALTER TABLE store_page_revision
    MODIFY detailed_description TEXT NOT NULL,
    MODIFY localizations_json TEXT NOT NULL,
    MODIFY genres_json TEXT NOT NULL,
    MODIFY tags_json TEXT NOT NULL,
    MODIFY developer VARCHAR(200) NOT NULL,
    MODIFY publisher VARCHAR(200) NOT NULL,
    MODIFY screenshots_json TEXT NOT NULL,
    MODIFY trailers_json TEXT NOT NULL,
    MODIFY supported_languages_json TEXT NOT NULL,
    MODIFY recommended_requirements VARCHAR(1000) NOT NULL,
    MODIFY features_json TEXT NOT NULL,
    MODIFY support_url VARCHAR(500) NOT NULL,
    MODIFY privacy_policy_url VARCHAR(500) NOT NULL,
    MODIFY eula_url VARCHAR(500) NOT NULL,
    MODIFY sales_countries_json TEXT NOT NULL,
    MODIFY prices_json TEXT NOT NULL;
