#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT_DIR"
secrets_file="$ROOT_DIR/build/api-demo/stack-secrets.env"

if [[ -f "$ROOT_DIR/.env" ]]; then
  set -a
  source "$ROOT_DIR/.env"
  set +a
fi

load_secrets() {
  if [[ -f "$secrets_file" ]]; then
    set -a
    # Generated by this script; the path is ignored by Git and readable only by the owner.
    source "$secrets_file"
    set +a
  fi
}

case "${1:-run}" in
  up)
    if [[ ! -f "$secrets_file" ]]; then
      if docker ps --format '{{.Names}}' | grep -qx 'stove-apps-auth-1'; then
        echo "실행 중인 앱 스택이 있습니다. 기존 인증 값을 유지해 run을 사용하거나, 별도 새 환경에서 up을 실행하세요." >&2
        exit 1
      fi
      mkdir -p "$(dirname "$secrets_file")"
      umask 077
      {
        printf 'AUTH_REVIEWER_PASSWORD=%s\n' "$(openssl rand -hex 20)"
        printf 'AUTH_ADMIN_PASSWORD=%s\n' "$(openssl rand -hex 20)"
        printf 'PG_CALLBACK_SECRET=%s\n' "$(openssl rand -hex 32)"
      } > "$secrets_file"
    fi
    load_secrets
    bash scripts/local-stack.sh demo-up
    exit 0
    ;;
  down)
    bash scripts/local-stack.sh demo-down
    exit 0
    ;;
  status)
    bash scripts/stack-wait.sh
    exit 0
    ;;
  run) ;;
  *)
    echo "사용법: $0 {up|run|status|down}" >&2
    exit 2
    ;;
esac

load_secrets

# Testcontainers needs the active Docker context on macOS as well as Linux.
if [[ -z "${DOCKER_HOST:-}" ]]; then
  detected_docker_host="$(docker context inspect --format '{{.Endpoints.docker.Host}}')"
  if [[ -n "$detected_docker_host" ]]; then
    export DOCKER_HOST="$detected_docker_host"
  fi
fi

run_dir="${API_DEMO_OUTPUT_DIR:-$ROOT_DIR/build/api-demo/$(date -u +%Y%m%dT%H%M%SZ)-$$}"
mkdir -p "$run_dir"
run_dir="$(cd "$run_dir" && pwd)"

echo "API 데모 결과: $run_dir"
bash scripts/stack-wait.sh 2>&1 | tee "$run_dir/stack-gate.log"
echo "서비스 단위·통합·OpenAPI 계약 테스트 실행 중 (로그: $run_dir/service-tests.log)"
if ! CI=1 ./gradlew test integrationTest --no-daemon --console=plain \
    > "$run_dir/service-tests.log" 2>&1; then
  tail -n 100 "$run_dir/service-tests.log" >&2
  exit 1
fi
echo "서비스 테스트 통과"

for run in 1 2; do
  report="$run_dir/run-$run.json"
  ./gradlew :e2e:apiDemoTest "-Dstove.e2e.report=$report" \
    --no-daemon --console=plain 2>&1 | tee "$run_dir/run-$run.log"
  [[ -s "$report" ]] || { echo "회차 $run 의 검증 증거가 없습니다: $report" >&2; exit 1; }
done

first_code="$(awk -F '"' '/"productCode"/ { print $4; exit }' "$run_dir/run-1.json")"
second_code="$(awk -F '"' '/"productCode"/ { print $4; exit }' "$run_dir/run-2.json")"
[[ -n "$first_code" && -n "$second_code" && "$first_code" != "$second_code" ]] || {
  echo "두 실행의 상품코드가 비어 있거나 같습니다" >&2
  exit 1
}

{
  echo "# API demo verification"
  echo
  revision="$(git rev-parse --short HEAD 2>/dev/null || echo uncommitted)"
  if [[ -n "$(git status --porcelain --untracked-files=normal 2>/dev/null)" ]]; then
    revision="$revision (working tree changes)"
  fi
  echo "- Source: $revision"
  echo "- UTC: $(date -u +%Y-%m-%dT%H:%M:%SZ)"
  echo "- Stack gate: passed (stack-gate.log)"
  echo "- Service unit, integration, OpenAPI contracts: passed (service-tests.log)"
  echo "- Run 1: $first_code (run-1.json, run-1.log)"
  echo "- Run 2: $second_code (run-2.json, run-2.log)"
  echo "- API journey: 57 executed checks per run, zero skipped"
} > "$run_dir/summary.md"

echo "두 회차 통과: $first_code / $second_code"
echo "결과 요약: $run_dir/summary.md"
